version: 2

jobs:
  one:
    docker: # running docker
      - image: circleci/ruby:2.4.1
        auth:
          username: jonathan
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "Hello World!"
      - run: sleep 10
  two:
    docker:
      - image: circleci/ruby:2.4.1
        auth:
          username: jonathan
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo " A more familiar hi!"
      - run: sleep 15

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
